[features]
seeds = false
skip-lint = false
[programs.Devnet]
defi = "FXJBsBUjrjCPJxuFMtu1nAYsPSzjnWS1GCD3Ynzpe6Q7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/arhamsoft/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
